export const quoteDetails = [
  {
    id: 1,
    pageName: "janitorial-services-nyc",
    title: "Janitorial Services",
    subtitle: "Reliable Commercial Janitorial Service for NYC Facilities",
    desc: "NYC's most trusted commercial cleaning crews — tailored to your schedule.",
    list: [
      "Fully Insured & Bonded",
      "Custom Schedules",
      "Eco-Friendly Products",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 2,
    pageName: "healthcare-facility-cleaning-nyc",
    title: "Janitorial Services",
    subtitle: "Reliable Commercial Janitorial Service for NYC Facilities",
    desc: "NYC's most trusted commercial cleaning crews — tailored to your schedule.",
    list: [
      "Fully Insured & Bonded",
      "Custom Schedules",
      "Eco-Friendly Products",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 3,
    pageName: "school-cleaning-nyc",
    title: "Janitorial Services",
    subtitle: "Reliable Commercial Janitorial Service for NYC Facilities",
    desc: "NYC's most trusted commercial cleaning crews — tailored to your schedule.",
    list: [
      "Fully Insured & Bonded",
      "Custom Schedules",
      "Eco-Friendly Products",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 4,
    pageName: "commercial-office-cleaning-nyc",
    title: "Janitorial Services",
    subtitle: "Reliable Commercial Janitorial Service for NYC Facilities",
    desc: "NYC's most trusted commercial cleaning crews — tailored to your schedule.",
    list: [
      "Fully Insured & Bonded",
      "Custom Schedules",
      "Eco-Friendly Products",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 5,
    pageName: "commercial-cleaning-services-manhattan-nyc",
    title: "Janitorial Services",
    subtitle: "Reliable Commercial Janitorial Service for NYC Facilities",
    desc: "NYC's most trusted commercial cleaning crews — tailored to your schedule.",
    list: [
      "Fully Insured & Bonded",
      "Custom Schedules",
      "Eco-Friendly Products",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 6,
    pageName: "commercial-cleaning-brooklyn",
    title: "Janitorial Services",
    subtitle: "Reliable Commercial Janitorial Service for NYC Facilities",
    desc: "NYC's most trusted commercial cleaning crews — tailored to your schedule.",
    list: [
      "Fully Insured & Bonded",
      "Custom Schedules",
      "Eco-Friendly Products",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 7,
    pageName: "commercial-cleaning-queens",
    title: "Janitorial Services",
    subtitle: "Reliable Commercial Janitorial Service for NYC Facilities",
    desc: "NYC's most trusted commercial cleaning crews — tailored to your schedule.",
    list: [
      "Fully Insured & Bonded",
      "Custom Schedules",
      "Eco-Friendly Products",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 8,
    pageName: "commercial-cleaning-bronx",
    title: "Janitorial Services",
    subtitle: "Reliable Commercial Janitorial Service for NYC Facilities",
    desc: "NYC's most trusted commercial cleaning crews — tailored to your schedule.",
    list: [
      "Fully Insured & Bonded",
      "Custom Schedules",
      "Eco-Friendly Products",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 9,
    pageName: "commercial-cleaning-staten-island",
    title: "Janitorial Services",
    subtitle: "Reliable Commercial Janitorial Service for NYC Facilities",
    desc: "NYC's most trusted commercial cleaning crews — tailored to your schedule.",
    list: [
      "Fully Insured & Bonded",
      "Custom Schedules",
      "Eco-Friendly Products",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 10,
    pageName: "commercial-cleaning-long-island",
    title: "Janitorial Services",
    subtitle: "Reliable Commercial Janitorial Service for NYC Facilities",
    desc: "NYC's most trusted commercial cleaning crews — tailored to your schedule.",
    list: [
      "Fully Insured & Bonded",
      "Custom Schedules",
      "Eco-Friendly Products",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  
];